Safe duck/move check in code
acm-ucr/aurora pull request #120
Opened 2023-07-20 04:33 UTC by SafeDuck

Left checkin page route blank:
![image](https://github.com/acm-ucr/hackathon-website/assets/49844738/3da7d6d4-8627-40b8-8124-ccd0fa47093c)

2023-07-20 04:48 UTC, menthy-wu requested changes

2023-07-20 04:48 UTC, menthy-wu commented on src/app/user/checkin/page.js
> +  return <div>Page</div>;
call checkin component

2023-07-21 03:54 UTC, SafeDuck commented on src/app/user/checkin/page.js
> +  return <div>Page</div>;
aight fasho

2023-07-22 02:37 UTC, shahdivyank approved these changes

2023-07-22 02:39 UTC, menthy-wu approved these changes

2023-07-22 02:44 UTC, merged