aligned checkboxes on teams page vertically
acm-ucr/aurora pull request #275
Opened 2023-08-16 18:05 UTC by isabellecelo

<img width="538" alt="Screenshot 2023-08-16 at 10 58 00 AM" src="https://github.com/acm-ucr/hackathon-website/assets/117539128/e18d438b-4af7-4409-8ca3-8325db30f44a">

closes Center Checkboxes

2023-08-16 18:54 UTC, shahdivyank requested changes

2023-08-16 18:54 UTC, shahdivyank commented on src/components/Admin/Team.jsx
> +          "border-t-[1px] border-hackathon-gray flex w-full focus:!ring-0 focus:!bg-hackathon-green-100 align-items-center " +
curious, what does the css look like for this ?

2023-08-16 18:54 UTC, shahdivyank commented on src/components/Admin/Team.jsx
> +          "border-t-[1px] border-hackathon-gray flex w-full focus:!ring-0 focus:!bg-hackathon-green-100 align-items-center " +
Can you put the CSS translation as a comment and then I can approve it

2023-08-16 18:55 UTC, shahdivyank commented
Fix merge conflict

2023-08-17 04:47 UTC, menthy-wu approved these changes, later dismissed

2023-08-17 22:13 UTC, shahdivyank commented
Only the checkbox should be aligned to the center, links/email and everything else should be aligned to the top

2023-08-19 19:20 UTC, shahdivyank commented
This is not needed anymore

2023-08-19 19:20 UTC, closed without merging