Create Feedback.jsx
acm-ucr/aurora pull request #278
Opened 2023-08-16 21:26 UTC by sophiiiapapaya

Not sure if the components are correctly imported/defined.

Need corrections for the name, type, value etc. for each question

2023-08-16 23:31 UTC, shahdivyank requested changes

2023-08-16 23:31 UTC, shahdivyank commented on src/components/Forms/Feedback.jsx
> +  const [mentor, setMentor] = useState(Helper);
don't call it mentor, make sure to change it for all feedback stuff. we also don't need to keep track of users since it can be an anonymous form

2023-08-20 03:00 UTC, sophiiiapapaya commented on src/components/Forms/Feedback.jsx
> +  const [mentor, setMentor] = useState(Helper);
@shahdivyank I made the changes

2023-08-20 19:13 UTC, shahdivyank approved these changes

2023-08-20 19:13 UTC, merged